services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
      - REDIS_URL=redis://redis:6379/
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AWS_LAMBDA_RUNTIME_API=localhost:8080
      - AWS_LAMBDA_FUNCTION_NAME=rust_lambda_fn
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=512
      - AWS_LAMBDA_FUNCTION_VERSION="$LATEST"
      - AWS_LAMBDA_LOG_GROUP_NAME=/aws/lambda/rust_lambda_fn
      - AWS_LAMBDA_LOG_STREAM_NAME=2025/04/11/[$LATEST]123456abcdef
      - AWS_REGION=us-east-1
      - AWS_EXECUTION_ENV=AWS_Lambda_provided
      - _AWS_XRAY_DAEMON_ADDRESS=127.0.0.1:2000
      - _AWS_XRAY_TRACE_ID="Root=1-67891233-abcdef012345678912345678"
      - LAMBDA_TASK_ROOT=/var/task
      - LAMBDA_RUNTIME_DIR=/var/runtime
    ports:
        - "9000:8080"
    entrypoint: ["/usr/local/bin/aws-lambda-rie", "/var/task/bootstrap"]
    depends_on:
      - redis
      - rabbitmq
    networks:
      - shared_network

  redis:
    image: redis:8.0-rc1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
          - shared_network

networks:
  shared_network:
    external: true
