services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
        - "${PORT}:8080"
    entrypoint: ["/usr/local/bin/aws-lambda-rie", "/var/task/bootstrap"]
    depends_on:
      - redis
      - rabbitmq
    networks:
      - shared_network

  redis:
    image: redis:8.0-rc1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
          - shared_network

networks:
  shared_network:
    external: true
